import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CartProvider } from "./context/CartContext";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "./ReactQueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900 `}
      >
        <CartProvider>
          <ReactQueryProvider>
            <div className="h-screen  flex flex-col    ">
              <Navbar />
              <div className="flex-grow overflow-scroll  ">
                {" "}
                <div className=" max-h-[50vh] relative">
                  <Toaster
                    position="top-center"
                    toastOptions={{ className: "mt-20" }}
                  />
                </div>
                {children}
              </div>
            </div>
          </ReactQueryProvider>
        </CartProvider>
      </body>
    </html>
  );
}
